/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment_1;

import java.io.*;

public class App {
    public static void main(String[] args) {
        DeliveryFactory deliveryFactory = new DeliveryFactory();

        Delivery method1 = deliveryFactory.getDelivery("Sea");
        method1.name();

        Delivery method2= deliveryFactory.getDelivery("Ground");
        method2.name();

        Delivery method3 = deliveryFactory.getDelivery("Air");
        method3.name();
    }
}
